### ISSUE TITLE
JDK 13 build fail: Error while generating Javadoc

### ISSUE THREAD

**Issue by Joseph-Cass** [eclipse/microprofile-fault-tolerance#512]
**My problem:** 
After updating my JDK version from 11 to 13, when I run `mvn clean install` I get the following build error:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MicroProfile Fault Tolerance 3.0-SNAPSHOT:
[INFO] 
[INFO] MicroProfile Fault Tolerance ....................... SUCCESS [  2.008 s]
[INFO] microProfile-fault-tolerance-api ................... FAILURE [  4.633 s]
[INFO] microprofile-fault-tolerance-tck ................... SKIPPED
[INFO] microprofile-fault-tolerance-spec .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.819 s
[INFO] Finished at: 2020-02-13T11:47:20Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project microprofile-fault-tolerance-api: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /Users/josephcass/Documents/libertyGit/microprofile-fault-tolerance/api/src/main/java/org/eclipse/microprofile/faulttolerance/FallbackHandler.java:26: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Usage</h3>
[ERROR]    ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/adoptopenjdk-13-openj9.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/josephcass/Documents/libertyGit/microprofile-fault-tolerance/api/target/apidocs' dir.
```
<br>

**My environment:**
When running JDK 11 I did not have this issue. I updated to the following OpenJDK version which caused the error:
```
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.2+8)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.0, JRE 13 Mac OS X amd64-64-Bit 20200118_155 (JIT enabled, AOT enabled)
OpenJ9   - 6968c18d7
OMR      - 7a1b0239a
JCL      - 9c5a41bd5f based on jdk-13.0.2+8)
```
<br>

**My solution:** 
I can fix this issue by refactoring all instances of `<h3>` to `<h2>` (There are only 2 instance throughout microprofile-fault-tolerance)

**Comment by Joseph-Cass** [comment]
I tested my fix of refactoring all instances of `<h3>` to `<h2>` against my old JDK 11 version for backward compatibility and it didn't create any issues.

If nobody else can foresee any issues with this change i'm happy to make a PR for it :)

**Test environment:**
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Mac OS X amd64-64-Bit 20200122_411 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)
```
<br>

**Test outcome:**
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for MicroProfile Fault Tolerance 3.0-SNAPSHOT:
[INFO] 
[INFO] MicroProfile Fault Tolerance ....................... SUCCESS [  1.616 s]
[INFO] microProfile-fault-tolerance-api ................... SUCCESS [  4.170 s]
[INFO] microprofile-fault-tolerance-tck ................... SUCCESS [ 13.488 s]
[INFO] microprofile-fault-tolerance-spec .................. SUCCESS [ 16.119 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.523 s
[INFO] Finished at: 2020-02-13T15:47:45Z
[INFO] ------------------------------------------------------------------------
```

**Comment by Joseph-Cass** [comment]
I have linked a PR with a potential solution
